In [4]:
import numpy as np

# numpy array

In [2]:
myList = [20,30,40]

In [3]:
np.array(myList)

array([20, 30, 40])

In [4]:
matrixList = [[10,20,30],[20,30,40],[30,40,50]]

In [5]:
matrixList[1][0]

20

In [6]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# numpy methods

# arange

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace

In [15]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [18]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

# eye

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

In [20]:
np.random.randn(4,4)

array([[-0.82468412,  0.25313453, -1.52638916, -1.01722352],
       [-2.1050795 ,  1.12918702, -0.96719276,  0.23030282],
       [ 0.5720069 ,  1.26905011, -0.20639928,  0.30760229],
       [ 1.62720387, -0.99707825, -0.46217754, -0.0249023 ]])

In [21]:
np.random.randint(1,10)

8

In [5]:
np.random.randint(1,10,5)

array([1, 5, 3, 8, 1])

In [6]:
myNumpy = np.arange(30)

In [7]:
myNumpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
myRandom = np.random.randint(0,100,20)

In [21]:
myRandom

array([42, 51, 64, 65, 16, 15, 64, 89, 44, 68, 23, 22, 15, 68,  7, 93, 90,
       63, 86, 44])

# numpy dizi methodları

In [15]:
myNumpy.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [16]:
myNumpy.max()

29

In [22]:
myRandom.max()

93

In [23]:
myRandom.min()

7

In [24]:
myRandom.argmax()

15

In [25]:
myRandom.argmin()

14

In [27]:
reshape = myNumpy.reshape(5,6)

In [28]:
reshape.shape

(5, 6)

# numpy indexler

In [29]:
benimDizim = np.arange(0,15)

In [30]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
benimDizim[5]

5

In [32]:
benimDizim[3:5]

array([3, 4])

In [33]:
benimDizim[3:8] = -5

In [34]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [35]:
baskaDizi = np.arange(0,24)

In [36]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [37]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [38]:
slicingDizisi = baskaDizi[4:9]

In [39]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [40]:
type(slicingDizisi)

numpy.ndarray

In [41]:
slicingDizisi[:] = 700

In [42]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [43]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [44]:
# içerisinden aldığım başka bir diziyi değiştirdim orjinali de etkilendi

In [45]:
ornekDizi = np.arange(0,24)

In [46]:
ornekDiziKopyasi = ornekDizi.copy()

In [47]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [50]:
ornekDiziKopyaSlicing[:] = 800

In [51]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [52]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [53]:
#orjinali etkilenmesin diye kopyasını alıp işlem yaptık

# matrix 

In [54]:
Listem = [[10,20,30],[20,30,40],[40,50,60]]

In [55]:
myMatrix = np.array(Listem)

In [56]:
myMatrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [57]:
myMatrix[0]

array([10, 20, 30])

In [59]:
myMatrix[1][2] #satır, sütun

40

In [61]:
myMatrix[1,2]

40

In [62]:
myMatrix[1:,2]

array([40, 60])

In [63]:
myMatrix[0:,2]

array([30, 40, 60])

In [64]:
myMatrix[2:,1:]

array([[50, 60]])

In [65]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [66]:
newMatrix = np.array(newList)

In [67]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
newMatrix[2]

array([10, 11, 12, 13, 14])

In [70]:
newMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [71]:
newMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

# numpy operasyonlar

In [74]:
yeniDizi = np.random.randint(1,100,20)

In [75]:
yeniDizi

array([74, 45, 57, 13, 65, 90, 20, 93, 89, 21, 79, 64, 37, 63, 12, 74, 34,
       28, 33, 12])

In [76]:
yeniDizi > 24

array([ True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False])

In [77]:
sonucDizisi = yeniDizi > 24 

In [78]:
sonucDizisi

array([ True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False])

In [79]:
yeniDizi[sonucDizisi]

array([74, 45, 57, 65, 90, 93, 89, 79, 64, 37, 63, 74, 34, 28, 33])

In [80]:
#sadece 24 den büyük olanları getirdi

In [81]:
yeniDizi[yeniDizi>24]

array([74, 45, 57, 65, 90, 93, 89, 79, 64, 37, 63, 74, 34, 28, 33])

In [82]:
sonDizi = np.arange(0,24)

In [83]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [84]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [85]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [86]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [87]:
sonDizi/sonDizi

C:\Users\can\AppData\Local\Temp\ipykernel_11708\1954055075.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [88]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [89]:
np.max(sonDizi)

23

In [90]:
np.min(sonDizi)

0